# Generated by Django 5.2.4 on 2025-07-13 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 12, 29, 23, 336060, tzinfo=datetime.timezone.utc)),
        ),
    ]
