# Generated by Django 5.2.3 on 2025-07-07 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_managers_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 12, 2, 24, 385787, tzinfo=datetime.timezone.utc)),
        ),
    ]
