# Generated by Django 5.2.4 on 2025-07-07 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 7, 12, 44, 56, 356080, tzinfo=datetime.timezone.utc)),
        ),
    ]
