# Generated by Django 5.2.3 on 2025-07-08 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 17, 47, 21, 861263, tzinfo=datetime.timezone.utc)),
        ),
    ]
