# Generated by Django 5.2.3 on 2025-07-13 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_contact_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 13, 10, 19, 53, 78103, tzinfo=datetime.timezone.utc)),
        ),
    ]
